services:
    app:
        build:
            context: .
        image: sprint5
        container_name: laravel_api
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
